services:
  ua-cloudlibrary:
    image: ${DOCKER_REGISTRY-}uacloudlibrary
    container_name: ua-cloudlibrary
    ports:
      - 8443:443
    build:
      context: .
      dockerfile: UACloudLibraryServer/Dockerfile
    networks:
      uanet:
        ipv4_address: 10.6.0.20
    environment:
        ConnectionStrings__CloudLibraryPostgreSQL: "Server=db;Username=${POSTGRESQL_USERNAME};Password=${POSTGRESQL_PASSWORD};Database=${POSTGRESQL_DATABASE};Port=5432;Ssl Mode=Prefer"
        ServicePassword: ${SERVICE_PASSWORD}
        PostgreSQLEndpoint: db
        APIKeyAuth: "true"
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - 5433:5432
    networks:
      uanet:
        ipv4_address: 10.6.0.21
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
  pgadmin:
    image: "dpage/pgadmin4"
    container_name: pgadmin
    ports:
      - 8088:80
    networks:
      uanet:
        ipv4_address: 10.6.0.22
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./local-dev-docker/docker_pgadmin_servers.json:/pgadmin4/servers.json
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'db:5432:*:${POSTGRESQL_USERNAME}:${POSTGRESQL_PASSWORD}' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    restart: unless-stopped

networks:
  uanet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
         gateway: 10.6.0.1