// <auto-generated />
using System;
using DataPlane.Sdk.Core.Data;
using DataPlane.Sdk.Core.Domain.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using DataPlane.Sdk.Core.Domain;

#nullable disable

namespace DataPlane.Sdk.Core.Migrations
{
    [DbContext(typeof(DataFlowContext))]
    partial class DataFlowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataPlane.Sdk.Core.Domain.DataFlow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AgreementId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CallbackAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DataAddress>("Destination")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsConsumer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeprovisionComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeprovisionRequested")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProvisionComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProvisionRequested")
                        .HasColumnType("boolean");

                    b.Property<string>("ParticipantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuntimeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DataAddress>("Source")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<TransferType>("TransferType")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DataFlows");
                });
#pragma warning restore 612, 618
        }
    }
}
