using System;
using System.ComponentModel.DataAnnotations;

namespace Opc.Ua.Cloud.Library.Models
{
    /// <summary>
    /// A singleton row holding the ESDC signing key generated by the server when no key was supplied
    /// through configuration. Persisting it is what makes the key stable: a key held only in memory
    /// dies with the process and differs per instance, so every ESDC issued before a restart (or by a
    /// sibling replica) would stop verifying.
    /// </summary>
    /// <remarks>
    /// This is a fallback, not the recommended production arrangement. A private key stored here also
    /// lives in every database backup and is visible to anything with database access. Supplying the
    /// key through <c>Dpp:Esdc:PrivateKeyPem</c> from a managed secret store keeps the signing material
    /// out of application data entirely; see the ESDC key management section of the README.
    /// </remarks>
    public class EsdcSigningKey
    {
        /// <summary>Fixed primary key: exactly one signing key row exists.</summary>
        public const int SingletonId = 1;

        [Key]
        public int Id { get; set; } = SingletonId;

        /// <summary>PKCS#8 private key PEM used to sign ESDCs.</summary>
        public string PrivateKeyPem { get; set; }

        /// <summary>When the key was generated, for rotation tracking and operator diagnostics.</summary>
        public DateTimeOffset CreatedAt { get; set; }
    }
}
